name: Test Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Bun.js 🛠️
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies 📦
        run: bun install

      - name: Build 🏗
        run: bun run build --filter pwa